---
SettingsSteps:
  enter Settings page:
    control_id: tablecellMyAccountSystemSettings
    control_action: click
    expectation: txtCountryDistrict

  enter Select Country page:
    control_id: txtCountryDistrict
    control_action: click
    expectation: uiviewSelectCountry

  select China:
    control_id: tablecellSelectCN
    control_action: click
    expectation: txtCountryDistrict&&设置

  select HongKong:
    control_id: tablecellSelectHK
    control_action: click
    expectation: txtCountryDistrict&&Settings

  enter ShoppingInfo page:
    control_id: tablecellShoppingInfo
    control_action: click
    expectation: uiviewShoppingInfo

  enter ShippingAddress page:
    control_id: tablecellShippingAddress
    control_action: click
    expectation: uiviewMyAddresses

  switch Shipping Address to China:
    control_id: Test_CN_Address
    control_action: click

  confirm Shipping Address selection:
    control_id: btnConfirm
    control_action: click
    expectation: uiviewShoppingInfo

  back to last page:
    control_id: btnArrowLeft
    control_action: click

  agree share location(optional):
    control_id: btnAgreeShareLocation
    control_action: click
    optional: true

  disagree share location(optional):
    control_id: btnDisagreeShareLocation
    control_action: click
    optional: true

  switch to test environment:
    control_id: switchMyAccountServerEnv
    control_action: click
    expectation: 切换后台 (当前测试环境)
